// User
export const ERROR_RECEIVE_USER = "ERROR_RECEIVE_USER";
export const REQUEST_USER = "REQUEST_USER";
export const RECEIVE_USER = "RECEIVE_USER";

export const ERROR_SIGN_IN = "ERROR_SIGN_IN";
export const REQUEST_SIGN_IN = "REQUEST_SIGN_IN";
export const SUCCESS_SIGN_IN = "SUCCESS_SIGN_IN";

export const ERROR_SIGN_UP = "ERROR_SIGN_UP";
export const REQUEST_SIGN_UP = "REQUEST_SIGN_UP";
export const SUCCESS_SIGN_UP = "SUCCESS_SIGN_UP";

export const REQUEST_SIGN_OUT = "REQUEST_SIGN_OUT";

// Employee
export const FETCH_EMPLOYEES_REQUESTED = "FETCH_EMPLOYEES_REQUESTED";
export const FETCH_EMPLOYEES_SUCCEEDED = "FETCH_EMPLOYEES_SUCCEEDED";
export const FETCH_EMPLOYEES_FAILED = "FETCH_EMPLOYEES_FAILED";
export const FETCH_ADD_EMPLOYEE_REQUESTED = "FETCH_ADD_EMPLOYEE_REQUESTED";
export const FETCH_ADD_EMPLOYEE_SUCCEEDED = "FETCH_ADD_EMPLOYEE_SUCCEEDED";
export const FETCH_ADD_EMPLOYEE_FAILED = "FETCH_ADD_EMPLOYEE_FAILED";
export const FETCH_UPDATE_EMPLOYEE_REQUESTED = "FETCH_UPDATE_EMPLOYEE_REQUESTED";
export const FETCH_UPDATE_EMPLOYEE_SUCCEEDED = "FETCH_UPDATE_EMPLOYEE_SUCCEEDED";
export const FETCH_UPDATE_EMPLOYEE_FAILED = "FETCH_UPDATE_EMPLOYEE_FAILED";
export const DELETE_EMPLOYEE_SUCCEEDED = "DELETE_EMPLOYEE_SUCCEEDED";

